import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import prisma from '../lib/prisma';

import styles from '../styles/Home.module.css';

const Home: NextPage = (props: any) => {
	const { posts } = props;
	console.log(props);

	const createPost = async (post: any) => {
		const respone = await fetch('/api/post', {
			method: 'POST',
			body: post,
		});
		if (!respone.ok) {
			throw new Error(respone.statusText);
		}
		return await respone.json();
	};
	const onSubmitPost = (e: any): void => {
		e.preventDefault();
	};
	interface test {
		title: string | undefined;
		descr: string | undefined;
	}
	const [state, setState] = useState<test>({
		title: '',
		descr: '',
	});

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			hello
			{JSON.stringify(state)}
			<form onSubmit={onSubmitPost}>
				<input type="text" name="title" value={state.title} onChange={(e) => setState({ title: e.target.value })} placeholder="title" />
				<input type="text" name="descr" value={state.descr} onChange={(e) => setState({ descr: e.target.value })} placeholder="descripton" />
				<button> submit</button>
			</form>
			<div style={{ borderTop: '5px solid #000', width: '100%', margin: 5 }}></div>
			<div style={{ borderTop: '5px solid #000', width: '100%', margin: 5 }}></div>
			<div style={{ borderTop: '5px solid #000', width: '100%', margin: 5 }}></div>
			{posts.map((post) => {
				return (
					<div key={post.id}>
						{post.title}
						{post.description}
					</div>
				);
			})}
		</div>
	);
};

export default Home;

export async function getServerSideProps() {
	const posts = await prisma.post.findMany();
	return {
		props: {
			posts,
		},
	};
}
